# Generated by Django 5.0.3 on 2024-03-21 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('category', models.CharField(choices=[('Industrial Supply', 'Industrial Supply'), ('Kitchen & Cooking', 'Kitchen & Cooking'), ('Construction Material', 'Construction Material')], max_length=30, null=True)),
                ('quantity', models.PositiveIntegerField(null=True)),
            ],
        ),
    ]
