# Generated by Django 5.0.3 on 2024-03-31 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_order_supplier_supplier_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier',
            field=models.CharField(choices=[('Total Gas', 'Total Gas'), ('Iron Sheets', 'Iron Sheets')], max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='AutoOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_quantity', models.PositiveIntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('is_auto_generated', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.product')),
            ],
        ),
    ]
