# Generated by Django 5.0.3 on 2024-03-31 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_product_low_stock_threshold_alter_supplier_supplier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='category',
            field=models.CharField(choices=[('Total Gas', 'Total Gas'), ('Iron Sheets', 'Iron Sheets')], max_length=200, null=True),
        ),
    ]
