# Generated by Django 5.0.3 on 2024-03-31 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_order_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='supplier',
            new_name='suppliers',
        ),
        migrations.AlterField(
            model_name='order',
            name='category',
            field=models.CharField(choices=[('Industrial Supply', 'Industrial Supply'), ('Kitchen & Cooking', 'Kitchen & Cooking'), ('Construction Material', 'Construction Material'), ('Cleaning and Janitorial Supplies', 'Cleaning and Janitorial Supplies'), ('Maintenance and Repair', 'Maintenance and Repair'), ('Electronics', 'Electronics'), ('Telecommunications', 'Telecommunications'), ('Electrical and Lighting', 'Electrical and Lighting'), ('Safety and Security', 'Safety and Security')], max_length=200, null=True),
        ),
    ]
