# Generated by Django 5.0.4 on 2024-04-13 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_remove_supplier_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.product'),
        ),
    ]
