# Generated by Django 5.0.4 on 2024-04-13 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_supplier_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='product',
        ),
    ]
