# Generated by Django 5.0.4 on 2024-04-13 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_remove_supplier_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='suppliers',
        ),
        migrations.AddField(
            model_name='supplier',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.product'),
        ),
    ]
