# Generated by Django 5.0.4 on 2024-04-14 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_remove_supplier_suppliers_supplier_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoorder',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.supplier'),
        ),
    ]
